### ISSUE TITLE
Some schools are duplicated between districts

### ISSUE THREAD

**Issue by davidlago** [davidlago/mass-edu-data-challenge#10]
Some schools from different districts share the exact same name. Also, some schools have a very generic name such as 'South Elementary'... we should always pre-pend the district name so that there is no confusion.

**Comment by Butterwell** [comment]
Post-pend with a dash instead?
South Elementary - Waltham
or parentheses?
South Elementary (Waltham)

**Comment by davidlago** [comment]
I suggested pre-pend because sorting alphabetically will group them by district...

**Comment by Butterwell** [comment]
Ah. sounds good. The typed part is bolded, so it's obvious what's going on.

**Comment by davidlago** [comment]
So, maybe I didn't do a good job explaining this before :)

The pre-pending I was going to do in the client side... so the back end info that I need in each document is:

`org_code`
`org_name`
`district_code`
`district_name`

This way, I iterate through the list and build the text for the drop-down as `{district_name} - {org_name}`, and upon selection I send to my function the `{org_code}`. But storing this 4 fields at the root of every school record, will allow us to do searches for a particular school, and then gather more info for its particular district. Her is an example:
- Someone selects school from the dropdown school _Boston - Mary Lyon_
- We know the selected value is `org_code`, so we query our api for it
- We know the selected school's district is `district_code` so we launch a second query for that

After this simple process, we have all the data about a school and its district. I think that incorporating the field `district_code` in the main level, as opposed to pre-pending it to the `org_name` would be a more convenient solution.

Thoughts?

**Comment by Butterwell** [comment]
I thought that might be the case, but I simply picked the longest school
name from all the choices and that's what we got. For this pass I was going
for completeness only. If there are any blanks, then we don't have any data.

I'll have another go at this this evening, and fill in the fields as
suggested, with one more that is the current (long) school name:
org_name_long

**Comment by davidlago** [comment]
That sound great! Thanks for such a quick response :+1:

I'll re-run it when it's done, and hopefully this weekend I can get started with presenting the data in a less JSON-y way on the screen :smile:

**Comment by Butterwell** [comment]
That was a bear. Inconsistencies all over the place because schools get
renamed. Went with name with the most recent year, but that might not do
the right thing in some cases, but every school and district should have a
name. No org_name_long. Of course, if you see any problems, let me know.

**Comment by davidlago** [comment]
Great work!!
