### ISSUE TITLE
A lot of schools not populating org_name

### ISSUE THREAD

**Issue by davidlago** [davidlago/mass-edu-data-challenge#11]
Example of one:

http://massedu.info/api/schools/03080830

It has SCHOOL_NAME in the document, but it didn't make it to the org_code field.

**Comment by Butterwell** [comment]
Yes, it's likely I only loaded public schools. It's from the
non_public_school_report.

In some of the databases, the name is uppercase and space padded. I'll fix
all the ones like this.

**Comment by davidlago** [comment]
Still a good number that didn't load the org_name in this run. Example:

http://www.massedu.info/api/schools/00350450

**Comment by Butterwell** [comment]
Okay, then. How many nulls do we have?

**Comment by davidlago** [comment]
489 total...
